name: cml-2020
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - numpy
  - pip
  - pandas
  - pyarrow
  - python-graphviz
  - scikit-learn
  - matplotlib
  - seaborn
  - pip:
    - onnxmltools
    - onnxruntime
